### PR TITLE
feat: add Either.tap, Either.tapLeft

### PR DESCRIPTION
**Pull request by denizdogan**

### CODE REVIEW

**Comment by pixeleet** [comment]
I think the way to go about it would be to add a utility function `tap` in `fn.ts`.
That would serve as the base of then adding `tap` and `tapLeft` on the TypeClasses that people most likely to need It on.

- [ ] Async
- [ ] AsyncEither
- [x] Either 
- [ ] Promise

@baetheus any thoughts?

An alternative thought I have as I'm writing this is that this could also be encapsulated in a Functor-like TypeClass.
Then I guess everything that implements Functor would implement it.

@denizdogan Thank you for your contribution.
Please try to add Documentation/Examples along the lines of:
/**
 * Run a side-effect on the Right side of an Either
 * ```ts
 * import { pipe } from "./fn.ts"
 * import { map, right, tap } from "./either.ts"
 * import { assertEquals } from "https://deno.land/std/testing/asserts.ts" 
 * 
 * const log = (a: unknown) => console.log(a);
 * const comp = pipe(right(1), log)
 * 
 * assertEquals(comp, right(1));
 * ```
 */

**Comment by baetheus** [comment]
Hello @denizdogan, thanks for the PR! Tap is a pretty nice tool to have to break out of some of the more crufty lazy/functional workflows. In general, I find it's best to implement tap as a derivation from Monad as this cuts down on some work. Specifically, something like:

```ts
import { Kind, $ } from "./kind.ts";

export function createTap<U extends Kind>(
  { of, chain }: Monad<U>,
): <A>(
  fn: (value: A) => void,
) => <B = never, C = never, D = unknown, E = unknown>(
  ua: $<U, [A, B, C], [D], [E]>,
) => $<U, [A, B, C], [D], [E]> {
  return (fn) =>
    chain((a) => {
      fn(a);
      return of(a);
    });
}

import { MonadOption } from "./option.ts";
const tapOption = createTap(MonadOption);

import { MonadEither } from "./either.ts";
const tapEither = createTap(MonadEither);

// ...etc
```

I'm finally back and am putting a bunch of time aside for the next month for programming projects so I will probably be implementing this in fun over a new set of typeclasses, so I probably won't be accepting PRs for a bit. But, again, thank you for your interest and contribution and please feel free to fork or use the project however you want!

**Comment by baetheus** [comment]
Additionally, one could also use Applicative, with `of` and `map` to do this, but it feels a little less "right" to me.

**Comment by pixeleet** [comment]
@denizdogan If you want to run experiments, I often do it in @type-driven/fun fork. 
Happy to look at adding Tap there.

**Comment by baetheus** [comment]
Yeah, my life is a state of transition right now where I get pulled away from programming often. Personally, I think fun is in good enough shape for my use, but I understand that some have come to rely on it. I don't really have time for hours of documentation anymore (especially since I don't enjoy it as much as I used to). So, if you really wanted to help me that would be the best place to start.

@pixeleet and I have talked about a few potential futures for fun, one of which is a fork that he manages. Ultimately, this is a low priority project for me and more of something I do for fun when I have time. What I'm trying to say is that it would be a good thing to keep this in mind when setting your expectations.

Again, thanks for the PR. I'm in the middle (hopefully I'll finish in July) of a pretty big restructure for fun 2.0 that will be renaming many many things. I'm kind of on the fence about it this week and will try to reach out via discussion to see if it's even worth continuing or if I'm just bike shedding with a couple of people.

**Pull request closed without merging**
